---
title: "Download package"
author: "Ming"
date: "2020/3/25"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## R Markdown
```{r}
library(googlesheets4)
```



```{r}
`我的年紀`<-20
 my_age<-`我的年紀`
```


```{r}
num1 <- 5
vNum1 <- c(2,5)
vNum2 <- c(2,5)
vNum2 <- c(2,num1)
```

```{r}
vNum1 <- c(-1,5)
vNum2 <- c(2,3)
vNum3 <- c(vNum1,vNum2)
vNum4 <- c(-1,5,2,3)
vNum5 <- c(c(-1,5),c(2,3))
```

```{r}
vNum1 <- c(-1,5)
vNum2 <- c(2,3)
vNum4 <- c() # 空向量
```

```{r}
vNum3 <- c(vNum2, vNum1)
vNum4 <- c(vNum4, vNum1) # 向量疊代 （recursive vector concatenate）
```

```{r}
char1<-c("你好")
char2<-c('你好')
```

```{r}
Hesaied <- "他說:'今天多了一個確診'"
Hesaied <- "他說:\'今天多了一個確診\'"
```

```{r}
library(httr)
library(dplyr)
GET("https://api.github.com/repos/tpemartin/108-2-56-inclass-practice/commits")%>%
content() %>%
View()
```

```{r}
library(googlesheets4)
`出席狀況表單網址` <-"https://docs.google.com/spreadsheets/d/1EAG49qDKPWWi0ebkVr29TLrvVnoBPfkvxYY-J3xLAHY/edit#gid=458686645"# 缺乏定義值
ss <- as_sheets_id(`出席狀況表單網址`)
homework_sheet <- sheets_read(ss,sheet=1)
```

