---
title: "2020-3-31"
author: "Ming"
date: "2020/4/8"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## List

```{r}
vectorExample <- c(2 ,6 ,7)
listExample <- list(2 ,6 ,7)

print(vectorExample)
print(listExample)
```

```{r}
#用vector儲存
C("2020-03-31T13:40:55Z",
  "一芳",
  "2",
  "水果茶")
```


```{r}
#用List儲存
library(lubridate)
`小明交易1` <- list(
  ymd_hms("2020-03-31T13:40:55Z"), # Date/Time class
  "一芳", # character
  2, # numeric
  "水果茶" # character
)
print(`小明交易1`)
```

```{r}
# list含兩個vectors
`小明108學年課表A` <- list(
  c("108-1","高級會計學","高等統計學"),
  c("108-2","食在拉丁美洲")
)
print(`小明108學年課表A`)
```

```{r}
# list含兩個lists
`小明108學年課表B` <- list(
  list("108-1","高級會計學","高等統計學"),
  list("108-2","食在拉丁美洲")
)
print(`小明108學年課表B`)
```

#nest list
```{r}
# list含兩個lists, 子層list又各含兩個vectors
`小明108學年課表C` <- list(
  list(
    c("108-1"), # 可只寫 "108-1"
    c("高級會計學","高等統計學")
       ),
  list(
    c("108-2"),
    c("食在拉丁美洲")
  )
)
print(`小明108學年課表C`)
```

#物件值可以取名
```{r}
# list含兩個lists, 子層list又各含兩個vectors
`小明108學年課表D` <- list(
  `上學期`=list(
    semester=c("108-1"), # 可只寫 "108-1"
    courses=c("高級會計學","高等統計學")
       ),
  `下學期`=list(
    semester=c("108-2"),
    courses=c("食在拉丁美洲")
  )
)
print(`小明108學年課表D`)
```

#沒命名上下學期
```{r}
`小明108學年課表D` <- list(
  list(
    semester=c("108-1"), # 可只寫 "108-1"
    courses=c("高級會計學","高等統計學")
       ),
  list(
    semester=c("108-2"),
    courses=c("食在拉丁美洲")
  )
)
print(`小明108學年課表D`)
```

## Github Commit
```{r}
commit <- list(
  author = list(
    name = "Martin老師",
    email = "mtlin@gm.ntpu.edu.tw",
    time =  ymd_hms("2020-03-25T07:17:40Z")),
  committer = list(
    name = "emilyluckey",
    email = "emily007@gmail.com",
    time = ymd_hms("2020-03-26T08:18:40Z")
  ),
  message = "update"
)
print(commit)
```

```{r}
browseURL("https://api.github.com/repos/tpemartin/108-2-56-inclass-practice/commits") 
```

```{r}
library(jsonlite) #不少同學這行會有Error，還記得如何排除嗎？
toJSON(commit)
```

```{r}
library(lubridate)
`氣溫預報` <-list(
  `台北市` = list(
    date = list(
      today = ymd("2020-03-31"), 
      tomorrow = ymd("2020-04-01")
    ), 
    highest = 25, 
    lowest = 18
  ), 
  `新北市` = list(
    date = list(
      today = ymd("2020-03-31"), 
      tomorrow = ymd("2020-04-01")
    ), 
    higest = 24, 
    lowest = 15
  )
)
print(`氣溫預報`)
```

```{r}
library(jsonlite)
fromJSON("https://opendata.cwb.gov.tw/fileapi/v1/opendataapi/F-C0032-001?Authorization=rdec-key-123-45678-011121314&format=JSON") ->
  weather_next36hours
```

##3-7
```{r}
save(commit,listExample,`小明108學年課表D`,
     file = "today.Rda")
```














