---
title: "2020-3-25"
author: "Ming"
date: "2020/4/7"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```




```{r}
C('aa','bb','cc')
C('1','2','55')
```

```{r}
C("小明今年歲數是","25")
```

```{r}
# 10位學生的主系
majors10_char <- c('經濟學系','社會學系','社會學系','經濟學系','經濟學系','社會學系','經濟學系','經濟學系','經濟學系','社會學系')

typeof(majors10_char)
class(majors10_char)
```

```{r}
majors10_factor <- factor(majors10_char)
# 或
majors10_factor <- factor(
  c('經濟學系','社會學系','社會學系','經濟學系','經濟學系','社會學系','經濟學系','經濟學系','經濟學系','社會學系')
)

typeof(majors10_factor)
class(majors10_factor)
```

```{r}
levels(majors10_factor)
```

```{r}
stringInteger <- c("1","2","-11")
class(stringInteger) # 無法進行數值運算
numericInteger <- as.numeric(stringInteger)
as.numeric(stringInteger)+2
```

```{r}
stringInteger <- c(1,2,-11)
class(stringInteger) # 無法進行數值運算
stringInteger+2
```

exercise
```{r}
studentId <- c(410773002, 410773015)
studentId <- as.character(studentId)
class(studentId)
```

##Date/Time

```{r}
browseURL("https://docs.google.com/spreadsheets/d/1EAG49qDKPWWi0ebkVr29TLrvVnoBPfkvxYY-J3xLAHY/edit#gid=458686645")
```

```{r}
library(lubridate)
```

台北 2020-03-18 13:52:40
```{r}
tpeDateTime <- ymd_hms("2020-03-18 13:52:40",tz="Asia/Taipei")
tpeDateTime
class(tpeDateTime)
typeof(tpeDateTime)
as.double(tpeDateTime)
```

葡萄牙 Mar.18, 2020 05:52:40
```{r}
pgDateTime <- mdy_hms("Mar.18, 2020 05:52:40",tz="Europe/Lisbon")
pgDateTime
class(pgDateTime)
typeof(pgDateTime)
as.double(tpeDateTime)
as.double(pgDateTime)
```
##看到TZ就不用with_tz,因為本身就是UTC時區

```{r}
with_tz(tpeDateTime, tzone ="UTC")
with_tz(pgDateTime, tzone ="UTC")
```

```{r}
studentTime <- c(ymd_hms("2020-03-04T06:56:29Z"),
                 ymd_hms("2020-03-11 14:16:43",tz="Asia/Taipei"),
                 ymd_hms("2020-03-11 14:34:33",tz="Asia/Taipei"))
studentTime
```








